manifest = "3f6ed2a0d9b2dc386e1b608e1c8e9d991b4533fdff27de3d1ba19f980194ee8e"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.30.1" ]
revision = "211cb1839d5488e44299309a5af011b0a9dff8d3"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.30.1" ]
revision = "5ffdf499e338c885abf953360a334b3d3ba71c96"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.30.1" ]
revision = "a31a71bb5ec767d069628c8d6f26c4a908b9d8d2"
