manifest = "835275c0052d27233506dcbc42db71fad575721ba7d8c8b4e414a13c5d89b1d8"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.38.0" ]
revision = "f129de05f396dc4d6e5460a69f648766659d4e09"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.38.0" ]
revision = "be230f24a809ac41e584cfd6d843485073012a80"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.38.0" ]
revision = "052bc304465323f02bea64dca87d3db7c07b457b"
